language: php
php:
  - 5.5
  - 5.6
env:
  - MAGENTO_VERSION=magento-ce-1.9.1.0
  - MAGENTO_VERSION=magento-ce-1.9.1.1
  - MAGENTO_VERSION=magento-ce-1.9.2.1
  - MAGENTO_VERSION=magento-ce-1.9.2.2
	
before_install:
- php /home/travis/.phpenv/versions/5.6/bin/composer self-update
- mysql -e "create database IF NOT EXISTS test;" -uroot
install:
  - composer install
  curl https://gordonlesti.com/"$MAGE".tar.gz | tar xz
  - mv $MAGE magento 
  - rm -rf var/cache/*
  - cd magento
  - wget https://raw.githubusercontent.com/colinmollenhour/modman/master/modman
  - chmod +x modman
  - ./modman init
before_script:
  - ./modman clone https://github.com/ngoctuanit07/magento-sqlserver.git
script: php vendor/bin/phpunit
services:
  - mysql